name: Test automation
on:
  issue_comment:
    types: [created]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    if: ${{ startsWith(github.event.comment.body, '/test') }}
    steps:
      - name: set repo name
        run: |
          x=`echo ${{ github.event.comment.body }} | head -1`; y=`echo $x | sed -E 's/^\/test[[:space:]]*(.*)$/\1/g' | tr -d '\r' | awk '{$1=$1};1'`; z=($y); a=`echo "${z[0]:-$DEFAULT_REPO}" | sed -E "s/^($DEFAULT_OWNER\/)?(.*)$/$DEFAULT_OWNER\/\2/g"`
          echo "REPO_NAME=$a" >> $GITHUB_ENV
        env:
          DEFAULT_OWNER: msgibble
          DEFAULT_REPO: ${{ github.event.repository.name }}
      - name: output repo name
        run: echo $REPO_NAME
      - name: validate repo name
        run: echo $REPO_NAME
      - name: validate author
        run: echo "${{ github.event.comment.author_association }}"
      - name: non-committing copy issue
        run: |
          echo "${{ github.event.issue.title }}"
          echo "${{ github.event.issue.body }}"
          echo "${{ github.event.issue.labels }}"
          echo "${{ github.event.issue.milestone }}"
      - name: copy issue
        run: |
          gh issue create --title "${{ github.event.issue.title }}" --body "${{ github.event.issue.body }}" --repo "$REPO_NAME"
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
