name: Test automation
on:
  issue_comment:
    types: [created]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    if: ${{ startsWith(github.event.comment.body, '/test') }}
    steps:
      - name: set repo name
        run: echo "REPO_NAME=$(x='${{ github.event.comment.body }}';y=${x%$'\n'*}; echo $y | sed 's/^\/test[[:space:]]\?\(.*\)/\1/g')" >> $GITHUB_ENV
      - name: output repo name
        run: echo $REPO_NAME
      - name: validate repo name
        run: echo $REPO_NAME
      - name: validate author
        run: echo "${{ github.event.comment.author_association }}"
      - name: non-committing copy issue
        run: |
          echo "${{ github.event.issue.title }}"
          echo "${{ github.event.issue.body }}"
          echo "${{ github.event.issue.labels }}"
          echo "${{ github.event.issue.milestone }}"
      - name: copy issue
        run: |
          gh issue create --title "${{ github.event.issue.title }}" --body "${{ github.event.issue.body }}" --repo msgibble/tt-server
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
