name: Test automation
on:
  issue_comment:
    types: [created]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: ${{ startsWith(github.event.comment.body, '/test') }}
    steps:
      - name: setting repo
        env:
          REPO_NAME: x=`echo "${{ github.event.comment.body }}"`;y=${x%$'\n'*}; echo $y | sed 's/^\/test[[:space:]]\?\(.*\)/\1/g'
      - name: printing repo
        run: echo "$REPO_Name"
