name: Test automation
on:
  issue_comment:
    types: [created]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      COMMENT_BODY: ${{ github.event.comment.body }}    
    steps:
      - name: update assignee
        if: ${{ startsWith(env.COMMENT_BODY, '/test') && !contains(github.event.issue.assignees.*.login, github.event.comment.user.login) }}
        run: |
          echo "Assigning to ${{ github.event.comment.user.login }}"
          gh issue edit ${{ github.event.issue.number }} --repo "${{ github.event.repository.full_name }}" --add-assignee "${{ github.event.comment.user.login }}"
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: set repo name
        if: ${{ startsWith(env.COMMENT_BODY, '/test') }}
        run: |
          x=`echo "$COMMENT_BODY" | head -1`
          y=`echo $x | sed -E 's/^\/test[[:space:]]*(.*)$/\1/g' | tr -d '\r' | awk '{$1=$1};1'`
          z=($y)
          a=`echo "${z[0]:-$DEFAULT_REPO}" | sed -E "s/^($DEFAULT_OWNER\/)?(.*)$/$DEFAULT_OWNER\/\2/g"`
          echo "REPO_NAME=$a" >> $GITHUB_ENV
          echo "Repository name set to $a"
        env:
          DEFAULT_OWNER: msgibble
          DEFAULT_REPO: ${{ github.event.repository.name }}
      - name: validate repo name
        if: ${{ startsWith(env.COMMENT_BODY, '/test') }}
        run: |
          gh repo view "$REPO_NAME"
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: determine labels
        if: ${{ startsWith(env.COMMENT_BODY, '/test') && env.REPO_NAME != env.DEFAULT_REPO }}
        run: |
          array_one=${{ github.event.issue.labels.*.name }}
          echo "${array_one[*]}"
          array_two=`gh labels list --repo "$REPO_NAME"`
          echo "${array_two[*]}"
          IFS=$'\n'; set -f
          intersection=($(comm -12 <(
           printf '%s\n' "${array_one[@]}" | sort) <(
           printf '%s\n' "${array_two[@]}" | sort)))

          echo "${intersection[*]}"
      - name: copy issue
        if: ${{ startsWith(env.COMMENT_BODY, '/test') }}
        run: |
          new_issue_body="$ISSUE_BODY"$'\n'
          new_issue_body+="> This issue was copied from [#${{ github.event.issue.number }}](${{ github.event.issue.html_url }}) by @${{ github.event.comment.user.login }}."
          
          gh issue create --title "$ISSUE_TITLE" --body "$new_issue_body" --label "`echo ${{ join(github.event.issue.labels.*.name, ',') }}`" --milestone "$MILESTONE_TITLE" --assignee "${{ github.event.comment.user.login }}" --repo "$REPO_NAME"
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          MILESTONE_TITLE: ${{ github.event.issue.milestone.title }}
          
