name: Test automation
on:
  issue_comment:
    types: [created]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: ${{ github.event.bodyText == '/test' }}
    steps:
      - name: checking env
        run: echo ${{ github.event.issue.number }}
