name: Test automation
on:
  issue_comment:
    types: [created]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: ${{ startsWith(github.event.comment.body, '/test') }}
    steps:
      - name: checking env
        run: echo ${{ github.event.issue.url }}
